### ISSUE TITLE
CI 환경에서 비밀 값들이 노출됨

### ISSUE THREAD

**Issue by yeojin-dev** [LeeHanYeong/django-json-secrets#1]
Pull request에 대한 Travis CI 빌드시 비밀 값들이 그대로 출력됩니다. 환경에 따라서 출력하지 않도록 하는 기능이 필요할 것 같습니다. 아니면 README.md에서 안내를 해도 좋고요.

**Comment by LeeHanYeong** [comment]
풀리퀘 보내주세요 ><

**Comment by yeojin-dev** [comment]
#2 
리뷰 부탁드립니다! 😆
